version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_final
    environment:
      POSTGRES_DB: payment_gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gateway_user -d payment_gateway" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_final
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_final
    environment:
      DATABASE_URL: postgresql://gateway_user:gateway_pass@postgres:5432/payment_gateway
      REDIS_URL: redis://redis:6379
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/test/jobs/status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worker_final
    command: [ "npm", "run", "worker" ]
    environment:
      DATABASE_URL: postgresql://gateway_user:gateway_pass@postgres:5432/payment_gateway
      REDIS_URL: redis://redis:6379
      TEST_MODE: "true"
      WEBHOOK_RETRY_INTERVALS_TEST: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard_final
    ports:
      - "3000:3000"
    depends_on:
      - api

  checkout:
    build:
      context: ./checkout_page
    container_name: checkout_final
    ports:
      - "3001:3001"
    depends_on:
      - api

volumes:
  postgres_data:
